USE UNIVER;
SELECT FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT, ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT(4))), 2)
FROM FACULTY INNER JOIN GROUPS
ON FACULTY.FACULTY = GROUPS.FACULTY
INNER JOIN STUDENT
ON GROUPS.IDGROUP = STUDENT.IDGROUP
INNER JOIN PROGRESS
ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE FACULTY.FACULTY = 'ÒÎÂ'
GROUP BY CUBE(GROUPS.PROFESSION, PROGRESS.SUBJECT), FACULTY.FACULTY

 