SELECT DISTINCT PULPIT.PULPIT_NAME
FROM FACULTY INNER JOIN PULPIT
ON FACULTY.FACULTY = PULPIT.FACULTY
INNER JOIN PROFESSION
ON FACULTY.FACULTY = PROFESSION.FACULTY
WHERE PROFESSION.PROFESSION_NAME LIKE '%технологи%'