SELECT DISTINCT PULPIT.PULPIT_NAME
FROM FACULTY INNER JOIN PULPIT
ON FACULTY.FACULTY = PULPIT.FACULTY
WHERE FACULTY.FACULTY in (SELECT PROFESSION.FACULTY FROM PROFESSION 
WHERE PROFESSION.PROFESSION_NAME LIKE '%технологи%')