SELECT DISTINCT PULPIT.PULPIT_NAME
FROM FACULTY, PULPIT, PROFESSION
WHERE FACULTY.FACULTY = PULPIT.FACULTY
AND FACULTY.FACULTY in (SELECT PROFESSION.FACULTY FROM PROFESSION 
WHERE PROFESSION.PROFESSION_NAME LIKE '%технологи%')