--В какой-то конкретный день
SELECT IDSTUDENT, NAME, BDAY, DAY(BDAY)[День] 
FROM STUDENT a
WHERE DAY(a.BDAY) = (SELECT TOP 1 DAY(aa.BDAY) FROM STUDENT aa);

--Вообще все одинаковые дни
SELECT DISTINCT s1.IDSTUDENT, s1.NAME, s1.BDAY, DAY(s1.BDAY)[День] 
FROM STUDENT s1 INNER JOIN STUDENT s2
	ON DAY(s1.BDAY) = DAY(s2.BDAY) AND s1.IDSTUDENT != s2.IDSTUDENT
ORDER BY DAY(s1.BDAY) ASC