SELECT CASE
	WHEN NOTE BETWEEN 9 AND 10 THEN 'Отлично'
	WHEN NOTE BETWEEN 6 AND 8 THEN 'Хорошо'
	WHEN NOTE BETWEEN 4 AND 5 THEN 'Удовлетворительно'
	ELSE 'Неудовлетворительно'
END NOTE, count(*) [Notes]
	FROM PROGRESS p JOIN STUDENT s ON p.IDSTUDENT = s.IDSTUDENT JOIN GROUPS g ON s.IDGROUP = g.IDGROUP
			WHERE FACULTY = 'ИДиП'
GROUP BY CASE
	WHEN NOTE BETWEEN 9 AND 10 THEN 'Отлично'
	WHEN NOTE BETWEEN 6 AND 8 THEN 'Хорошо'
	WHEN NOTE BETWEEN 4 AND 5 THEN 'Удовлетворительно'
	ELSE 'Неудовлетворительно'
END ORDER BY NOTE DESC;