BEGIN TRY
UPDATE STUDENT SET IDGROUP = 'string' WHERE IDGROUP = 18
END TRY
BEGIN CATCH
PRINT 'Код ошибки:		' + CAST(ERROR_NUMBER() AS CHAR)
PRINT 'Сообщение:		' + ERROR_MESSAGE()
PRINT 'Номер строки:	' + CAST(ERROR_LINE() AS CHAR)
PRINT 'Имя процедуры:	' + ERROR_PROCEDURE()
PRINT 'Severity:		' + CAST(ERROR_SEVERITY() AS CHAR)
PRINT 'Метка ошибки:	' + CAST(ERROR_STATE() AS CHAR)
END CATCH