USE UNIVER;
SELECT *
FROM (SELECT CASE
			WHEN NOTE BETWEEN 1 AND 3 THEN '1-3'
			WHEN NOTE BETWEEN 4 AND 5 THEN '4-5'
			WHEN NOTE BETWEEN 6 AND 7 THEN '6-7'
			WHEN NOTE BETWEEN 8 AND 9 THEN '8-9'
			ELSE '10'
			END [NOTES], count(*) [COUNT_OF_NOTES]

FROM PROGRESS GROUP BY CASE
			WHEN NOTE BETWEEN 1 AND 3 THEN '1-3'
			WHEN NOTE BETWEEN 4 AND 5 THEN '4-5'
			WHEN NOTE BETWEEN 6 AND 7 THEN '6-7'
			WHEN NOTE BETWEEN 8 AND 9 THEN '8-9'
			ELSE '10'
			END) AS a

ORDER BY CASE [NOTES]
			WHEN '1-3' THEN 4
			WHEN '4-5' THEN 3
			WHEN '6-7' THEN 2
			WHEN '8-9' THEN 1
			ELSE 0
			END