USE UNIVER;
SELECT AUDITORIUM.AUDITORIUM_TYPE, 
MAX(AUDITORIUM.AUDITORIUM_CAPACITY)[MAX_CAPACITY],
MIN(AUDITORIUM.AUDITORIUM_CAPACITY)[MIN_CAPACITY],
AVG(AUDITORIUM.AUDITORIUM_CAPACITY)[AVG_CAPACITY],
SUM(AUDITORIUM.AUDITORIUM_CAPACITY)[SUM_OF_CAPACITIES],
COUNT(*)[COUNT_OF_AUDITORIES]
FROM AUDITORIUM INNER JOIN AUDITORIUM_TYPE
ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
GROUP BY AUDITORIUM.AUDITORIUM_TYPE;