USE UNIVER;
SELECT SUBJECT, (SELECT COUNT(*) FROM PROGRESS p2 WHERE p1.SUBJECT = p2.SUBJECT 
and p1.NOTE = p2.NOTE)[COUNT_OF_STUDENTS]
FROM PROGRESS p1
GROUP BY SUBJECT, IDSTUDENT, NOTE
HAVING p1.NOTE BETWEEN 8 AND 9;